"""lecturer

Revision ID: 05c526e58d23
Revises: 5035e48f17ed
Create Date: 2024-03-26 06:29:06.895170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05c526e58d23'
down_revision: Union[str, None] = '5035e48f17ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grades', sa.Column('subject_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'grades', 'subjects', ['subject_id'], ['subject_id'])
    op.add_column('lecturers', sa.Column('lecturer_name', sa.String(length=255), nullable=False))
    op.drop_constraint('lecturers_lectutrer_name_key', 'lecturers', type_='unique')
    op.create_unique_constraint(None, 'lecturers', ['lecturer_name'])
    op.drop_column('lecturers', 'lectutrer_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lecturers', sa.Column('lectutrer_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'lecturers', type_='unique')
    op.create_unique_constraint('lecturers_lectutrer_name_key', 'lecturers', ['lectutrer_name'])
    op.drop_column('lecturers', 'lecturer_name')
    op.drop_constraint(None, 'grades', type_='foreignkey')
    op.drop_column('grades', 'subject_id')
    # ### end Alembic commands ###
